name: Deploy Landing Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.TOKEN_LANDING_PAGE_AULA_BOOTSTRAP }}
          publish_dir: ./   # como é só HTML, o diretório raiz é suficiente
